version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    ports:
      - "8080:8080"
    volumes:
      - ./tdlib-db:/app/tdlib-db
    env_file:
      - .env
